# Copyright (c) 2023-2024 384(tm) Inc, All Rights Reserved.

# ergo "<name>.<your CF domain>.workers.dev"
name = "storage"

workers_dev = true
compatibility_date = "2024-01-29"
main = "./src/index.ts"

# Replace with your account id
account_id = '...'
usage_model = 'unbound'

# You need to set up these KV namespaces in the CF dashboard.
# The ledger namespace is shared with the channel server
kv_namespaces = [
  { binding = "LEDGER_NAMESPACE", id = "...", preview_id = "..." },
  { binding = "IMAGES_NAMESPACE", id = "...", preview_id = "..." },
  { binding = "PAGES_NAMESPACE", id = "...", preview_id = "..." },
]

[env.production]
name = "s" # default production channel name eg "s.<your CF domain>.workers.dev"
kv_namespaces = [
  { binding = "LEDGER_NAMESPACE", id = "...", preview_id = "..." },
  { binding = "IMAGES_NAMESPACE", id = "...", preview_id = "..." },
  { binding = "PAGES_NAMESPACE", id = "...", preview_id = "..." },
]

# note on debug flags: you can simply leave them false here and toggle them to
# true in the ''.dev.vars'' file; for details see
# https://developers.cloudflare.com/workers/configuration/environment-variables/

[vars]
VERSION="..."
ENVIRONMENT="development"
# privacy window is the deduplication regularity, default 2 weeks
PRIVACY_WINDOW=1209600
LOG_ERRORS=true
DEBUG_ON=false # low-noise debug output
VERBOSE_ON=false # noisier

[env.production.vars]
VERSION="..."
ENVIRONMENT="production"
PRIVACY_WINDOW=1209600 # 14 days (14 * 24 * 60 * 60 seconds)
LOG_ERRORS=true
DEBUG_ON=false
VERBOSE_ON=false
